/**
 * Mock Data for Operator App
 * 
 * Provides fake test data when the API is unavailable.
 */

export type MockBankId = 1 | 2 | 3 | 4 | 5;

export const mockJobs = [
  {
    id: "1",
    orderId: "PED-2024-001",
    model: "CP-3200",
    client: "Aceites del Norte S.A.",
    status: "GENERADA" as const,
    targetFlow: 3200,
    impeller: "320mm",
    bancoId: 1 as MockBankId, // Banco A
    createdAt: new Date("2024-01-15"),
    protocolSpec: {
      customerOrder: "PO-45678",
      jobDate: "2024-01-15",
      pumpQuantity: 2,
      workOrder: "OT-2024-001",
      itemNumber: "1",
      pumpType: "Centrífuga Horizontal",
      serialNumber: "SN-32001",
      suctionDiameter: 300,
      dischargeDiameter: 250,
      impellerDiameter: "320mm",
      sealType: "Mecánica doble",
      isVertical: false,
      motorBrand: "Siemens",
      motorType: "1LE1004-3AB21",
      motorPower: 315,
      motorSpeed: 1480,
      motorVoltage: 400,
    },
  },
  {
    id: "2",
    orderId: "PED-2024-002",
    model: "HM-1500",
    client: "Refinerías del Levante",
    status: "EN_PROCESO" as const,
    targetFlow: 1500,
    impeller: "280mm",
    bancoId: 2 as MockBankId, // Banco B
    createdAt: new Date("2024-01-16"),
    protocolSpec: {
      customerOrder: "PO-45679",
      jobDate: "2024-01-16",
      pumpQuantity: 1,
      workOrder: "OT-2024-002",
      itemNumber: "1",
      pumpType: "Horizontal Monobloco",
      serialNumber: "SN-15001",
      suctionDiameter: 200,
      dischargeDiameter: 150,
      impellerDiameter: "280mm",
      sealType: "Mecánica simple",
      isVertical: false,
      motorBrand: "ABB",
      motorType: "M3AA132M",
      motorPower: 160,
      motorSpeed: 1450,
      motorVoltage: 400,
    },
  },
  {
    id: "3",
    orderId: "PED-2024-003",
    model: "VT-800",
    client: "Agricultores Unidos Coop.",
    status: "GENERADA" as const,
    targetFlow: 800,
    impeller: "220mm",
    bancoId: 1 as MockBankId, // Banco A
    createdAt: new Date("2024-01-17"),
    protocolSpec: {
      customerOrder: "PO-45680",
      jobDate: "2024-01-17",
      pumpQuantity: 3,
      workOrder: "OT-2024-003",
      itemNumber: "1",
      pumpType: "Vertical Tina",
      serialNumber: "SN-08001",
      suctionDiameter: 150,
      dischargeDiameter: 125,
      impellerDiameter: "220mm",
      sealType: "Prensaestopas",
      isVertical: true,
      motorBrand: "WEG",
      motorType: "W22 Cast Iron",
      motorPower: 75,
      motorSpeed: 1750,
      motorVoltage: 380,
    },
  },
  {
    id: "4",
    orderId: "PED-2024-004",
    model: "CP-5000",
    client: "Petroquímica del Sur",
    status: "OK" as const,
    targetFlow: 5000,
    impeller: "400mm",
    bancoId: 3 as MockBankId, // Banco C
    createdAt: new Date("2024-01-10"),
    completedAt: new Date("2024-01-14"),
    protocolSpec: {
      customerOrder: "PO-45670",
      jobDate: "2024-01-10",
      pumpQuantity: 1,
      workOrder: "OT-2024-004",
      itemNumber: "1",
      pumpType: "Centrífuga Horizontal Doble",
      serialNumber: "SN-50001",
      suctionDiameter: 400,
      dischargeDiameter: 350,
      impellerDiameter: "400mm",
      sealType: "Mecánica doble API",
      isVertical: false,
      motorBrand: "Siemens",
      motorType: "1LA7074-4AB21",
      motorPower: 500,
      motorSpeed: 1490,
      motorVoltage: 690,
    },
  },
  {
    id: "5",
    orderId: "PED-2024-005",
    model: "SM-200",
    client: "Agua Municipal Barcelona",
    status: "GENERADA" as const,
    targetFlow: 200,
    impeller: "180mm",
    bancoId: 2 as MockBankId, // Banco B
    createdAt: new Date("2024-01-18"),
    protocolSpec: {
      customerOrder: "PO-45681",
      jobDate: "2024-01-18",
      pumpQuantity: 2,
      workOrder: "OT-2024-005",
      itemNumber: "1",
      pumpType: "Sumergible",
      serialNumber: "SN-02001",
      suctionDiameter: 100,
      dischargeDiameter: 80,
      impellerDiameter: "180mm",
      sealType: "Cierre hidráulico",
      isVertical: true,
      motorBrand: "KSB",
      motorType: "UP 30-200",
      motorPower: 30,
      motorSpeed: 2850,
      motorVoltage: 400,
    },
  },
  {
    id: "6",
    orderId: "PED-2024-006",
    model: "CP-2500",
    client: "Industrias Químicas Reunidas",
    status: "EN_PROCESO" as const,
    targetFlow: 2500,
    impeller: "300mm",
    bancoId: 1 as MockBankId, // Banco A
    createdAt: new Date("2024-01-19"),
    protocolSpec: {
      customerOrder: "PO-45682",
      jobDate: "2024-01-19",
      pumpQuantity: 1,
      workOrder: "OT-2024-006",
      itemNumber: "1",
      pumpType: "Centrífuga Horizontal",
      serialNumber: "SN-25001",
      suctionDiameter: 250,
      dischargeDiameter: 200,
      impellerDiameter: "300mm",
      sealType: "Mecánica doble",
      isVertical: false,
      motorBrand: "Siemens",
      motorType: "1LE1004-3AB21",
      motorPower: 250,
      motorSpeed: 1480,
      motorVoltage: 400,
    },
  },
  {
    id: "7",
    orderId: "PED-2024-007",
    model: "HM-1000",
    client: "Construcciones Hidráulicas S.L.",
    status: "GENERADA" as const,
    targetFlow: 1000,
    impeller: "250mm",
    bancoId: 5 as MockBankId, // Banco E
    createdAt: new Date("2024-01-20"),
    protocolSpec: {
      customerOrder: "PO-45683",
      jobDate: "2024-01-20",
      pumpQuantity: 2,
      workOrder: "OT-2024-007",
      itemNumber: "1",
      pumpType: "Horizontal Monobloco",
      serialNumber: "SN-10001",
      suctionDiameter: 180,
      dischargeDiameter: 125,
      impellerDiameter: "250mm",
      sealType: "Mecánica simple",
      isVertical: false,
      motorBrand: "ABB",
      motorType: "M3AA112M",
      motorPower: 110,
      motorSpeed: 1450,
      motorVoltage: 400,
    },
  },
  {
    id: "8",
    orderId: "PED-2024-008",
    model: "CP-4000",
    client: "Planta de Tratamiento Norte",
    status: "KO" as const,
    targetFlow: 4000,
    impeller: "380mm",
    bancoId: 4 as MockBankId, // Banco D
    createdAt: new Date("2024-01-08"),
    completedAt: new Date("2024-01-12"),
    protocolSpec: {
      customerOrder: "PO-45684",
      jobDate: "2024-01-08",
      pumpQuantity: 1,
      workOrder: "OT-2024-008",
      itemNumber: "1",
      pumpType: "Centrífuga Horizontal",
      serialNumber: "SN-40001",
      suctionDiameter: 350,
      dischargeDiameter: 300,
      impellerDiameter: "380mm",
      sealType: "Mecánica doble API",
      isVertical: false,
      motorBrand: "Siemens",
      motorType: "1LA7074-4AB21",
      motorPower: 400,
      motorSpeed: 1490,
      motorVoltage: 690,
    },
  },
];

export const mockBancos = [
  { id: 1, nombre: "Banco A", estado: true },
  { id: 2, nombre: "Banco B", estado: true },
  { id: 3, nombre: "Banco C", estado: true },
  { id: 4, nombre: "Banco D", estado: false },
  { id: 5, nombre: "Banco E", estado: true },
];

export const mockMotores = [
  { id: "M1", nombre: "Motor Principal 1", potencia: 315, rpm: 1480, bancoId: 1 },
  { id: "M2", nombre: "Motor Principal 2", potencia: 160, rpm: 1450, bancoId: 2 },
  { id: "M3", nombre: "Motor Principal 3", potencia: 75, rpm: 1750, bancoId: 3 },
  { id: "M4", nombre: "Motor Principal 5", potencia: 30, rpm: 2850, bancoId: 5 },
];

export const mockTelemetry = {
  pressure: 12.5,
  flow: 1500,
  temperature: 45,
  power: 180,
  npsh: 8.2,
  rpm: 1480,
  timestamp: Date.now(),
};

export const mockTestPoints = [
  { id: 1, targetFlow: 0, captured: true, capturedData: { ...mockTelemetry, flow: 0 } },
  { id: 2, targetFlow: 500, captured: true, capturedData: { ...mockTelemetry, flow: 495 } },
  { id: 3, targetFlow: 1000, captured: true, capturedData: { ...mockTelemetry, flow: 1002 } },
  { id: 4, targetFlow: 1500, captured: false, capturedData: undefined },
  { id: 5, targetFlow: 2000, captured: false, capturedData: undefined },
  { id: 6, targetFlow: 2500, captured: false, capturedData: undefined },
];

export function getBankLetter(bancoId: number): string {
  const letters = ['A', 'B', 'C', 'D', 'E'];
  return letters[bancoId - 1] || 'A';
}
